### ISSUE TITLE
Slack Namespace

### ISSUE THREAD

**Issue by svallory** [kevinsuh/toki#87]
Hi, sorry to bother... are you the owner of the Slack workspace toki.slack.com? If not, you can stop reading here.

I the founder of a nonprofit called Toki. We are still setting things up, so I don't have much proof to show for it, but it's real: https://www.facebook.com/Toki-Network-229849027571946/

I'm setting up the software we'll use and tried to register the workspace I mentioned above. Since the project has been inactive for some time, I though I would ask you if could give the workspace name up. Would you mind doing that?

**Comment by kevinsuh** [comment]
We aren’t. Our workspace was tokibot.slack.com

**Comment by svallory** [comment]
Ok, Thanks!
